version: '3.3'
services:

  server:
    build: ./server
    command: python main.py
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'

  client:
    build: ./client
    command: python main.py
